sudo: required

services:
- docker

before_install:
- VERSION=centos

script:
- docker build -t wisecloud/jenkins:${VERSION} .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wisecloud/jenkins:${VERSION}
  on:
    all_branches: true
    #condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
